FROM ubuntu:22.04

RUN apt update && apt install -y openssl

WORKDIR /app

RUN openssl genrsa -out server.key 2048 && \
    openssl req -new -x509 -key server.key -out server.crt -days 365 -subj "/CN=tls-server"

CMD openssl s_server -key server.key -cert server.crt -accept 8443